services:
  agentic-rag:
    container_name: agentic-rag-eval
    build: .
    ports:
      - "19010:8000"
    environment:
      - MILVUS_HOST=192.168.250.142
      - MILVUS_PORT=19530
      - MILVUS_DATABASE=eval
      - VLLM_API_URL=192.168.250.142
      - VLLM_EMBED_API_PORT=9005
      - VLLM_EMBED_MODEL_NAME=jinaai/jina-embeddings-v3
      - VLLM_RERANK_API_PORT=9008
      - VLLM_RERANK_MODEL_NAME=BAAI/bge-reranker-v2-m3
      - VLLM_GEN_API_PORT=9002
      - VLLM_GEN_MODEL_NAME=nvidia/Llama-4-Scout-17B-16E-Instruct-NVFP4
      - CUSTOM_JINA_API_PORT=9007
    volumes:
      - ./documents:/app/documents
