services:
  agentic-rag:
    container_name: agentic-rag
    build: .
    restart: unless-stopped
    ports:
      - "19008:8000"
    environment:
      - MILVUS_HOST=YOUR_MILVUS_HOST
      - MILVUS_PORT=YOUR_MILVUS_PORT
      - MILVUS_DATABASE=YOUR_MILVUS_DATABASE
      - VLLM_API_URL=YOUR_VLLM_API_URL
      - VLLM_EMBED_API_PORT=YOUR_VLLM_EMBED_API_PORT
      - VLLM_EMBED_MODEL_NAME=YOUR_VLLM_EMBED_MODEL_NAME
      - VLLM_RERANK_API_PORT=YOUR_VLLM_RERANK_API_PORT
      - VLLM_RERANK_MODEL_NAME=YOUR_VLLM_RERANK_MODEL_NAME
      - VLLM_GEN_API_PORT=YOUR_VLLM_GENERATION_API_PORT
      - VLLM_GEN_MODEL_NAME=YOUR_VLLM_GENERATION_MODEL_NAME
      - CUSTOM_JINA_API_PORT=YOUR_CUSTOM_JINA_API_PORT
    volumes:
      - ./documents:/app/documents
