from dotenv import load_dotenv
import os

load_dotenv()

MILVUS_HOST = os.getenv("MILVUS_HOST", "MILVUS_HOST")
MILVUS_PORT = int(os.getenv("MILVUS_PORT", "MILVUS_PORT"))
MILVUS_DATABASE = os.getenv("MILVUS_DATABASE", None)

VLLM_API_URL = os.getenv("VLLM_API_URL", "VLLM_API_URL")

VLLM_EMBED_API_PORT = int(os.getenv("VLLM_EMBED_API_PORT", "VLLM_EMBED_API_PORT"))
VLLM_EMBED_MODEL_NAME = os.getenv("VLLM_EMBED_MODEL_NAME", "VLLM_EMBED_MODEL_NAME")

VLLM_RERANK_API_PORT = int(os.getenv("VLLM_RERANK_API_PORT", "VLLM_RERANK_API_PORT"))
VLLM_RERANK_MODEL_NAME = os.getenv("VLLM_RERANK_MODEL_NAME", "VLLM_RERANK_MODEL_NAME")

VLLM_GEN_API_PORT = int(os.getenv("VLLM_GEN_API_PORT", "VLLM_GEN_API_PORT"))
VLLM_GEN_MODEL_NAME = os.getenv("VLLM_GEN_MODEL_NAME", "VLLM_GEN_MODEL_NAME")

CUSTOM_JINA_API_PORT = int(os.getenv("CUSTOM_JINA_API_PORT", "CUSTOM_JINA_API_PORT"))
