import pandas as pd
import sys
from pathlib import Path

# 1. SETUP
# Path to the detailed results CSV generated by your evaluation.py
# Update this filename to match your actual output file
csv_path = (
    Path(__file__).parent.parent.parent
    / "documents"
    / "train_evaluation_results_detailed_results.csv"
)

# Common phrases that indicate the model refused to answer (case-insensitive partial match)
REJECTION_PHRASES = [
    "no relevant information found",
    "no information available",
    "no information",
    "not mentioned",
    "does not provide",
    "i cannot answer",
    "no answer",
    "i'm sorry",
    "i am sorry",
    "does not contain",
    "knowledge base",
    "i don't know",
    "not possible",
    "not explicitly",
    "there is no",
    "there are no",
    "does not specify",
]


def calculate_confusion_matrix(file_path):
    if not file_path.exists():
        print(f"File not found: {file_path}")
        return

    print(f"Reading: {file_path}")
    df = pd.read_csv(file_path)

    tp = 0  # Correctly Answered (Found something when it should)
    tn = 0  # Correctly Rejected (Said "IDK" when it should)
    fp = 0  # Hallucination (Answered when it should have said "IDK")
    fn = 0  # Missed (Said "IDK" when there was an answer)

    results_breakdown = []

    for index, row in df.iterrows():
        # Clean the data
        # Ragas renames columns in output: ground_truth -> reference, answer -> response
        gt_col = "reference" if "reference" in df.columns else "ground_truth"
        ans_col = "response" if "response" in df.columns else "answer"
        q_col = "user_input" if "user_input" in df.columns else "question"

        gt = str(row.get(gt_col, "")).strip()
        prediction = str(row.get(ans_col, "")).strip()

        # LOGIC:
        # 1. Does a Ground Truth exist? (Is it answerable?)
        # Check for empty strings, 'nan', or empty brackets if cleaning failed
        has_ground_truth = (len(gt) > 0) and (
            gt.lower() != "nan") and (gt != "[]")

        # 2. Did the System provide an answer?
        # It answered if NONE of the rejection phrases are in the prediction (normalized to lower case)
        pred_lower = prediction.lower()
        system_provided_answer = not any(
            phrase in pred_lower for phrase in REJECTION_PHRASES
        )

        category = ""

        if has_ground_truth and system_provided_answer:
            tp += 1
            category = "TP"
        elif not has_ground_truth and not system_provided_answer:
            tn += 1
            category = "TN"
        elif not has_ground_truth and system_provided_answer:
            fp += 1
            category = "FP (Hallucination)"
        elif has_ground_truth and not system_provided_answer:
            fn += 1
            category = "FN (Retrieval Fail)"

        # Store for debugging inspection
        results_breakdown.append(
            {
                "question": row.get(q_col, "Unknown Question"),
                "category": category,
                "prediction_snippet": prediction[:50],
            }
        )

    # CALCULATE METRICS
    total = tp + tn + fp + fn
    if total == 0:
        print("Dataset is empty.")
        return

    accuracy = (tp + tn) / total
    # Avoid division by zero
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1_score = (
        2 * (precision * recall) / (precision + recall)
        if (precision + recall) > 0
        else 0
    )

    print("\n" + "=" * 30)
    print("CONFUSION MATRIX RESULTS")
    print("=" * 30)
    print(f"Total Rows: {total}")
    print(f"True Positives  (TP): {tp} \t(Correctly attempted answer)")
    print(f"True Negatives  (TN): {tn} \t(Correctly Refused)")
    print(f"False Positives (FP): {fp} \t(Hallucinated on unanswerable Q)")
    print(f"False Negatives (FN): {fn} \t(Failed to find existing answer)")
    print("-" * 30)
    print(f"Accuracy:  {accuracy:.2%}")
    print(f"Precision: {precision:.2%} (Trustworthiness of answers provided)")
    print(f"Recall:    {recall:.2%} (Ability to find answers that exist)")
    print(f"F1 Score:  {f1_score:.2%} (Harmonic mean of Precision and Recall)")
    print("=" * 30)

    # Show failures
    print("\n--- SAMPLE FAILURES (FN - Missed Answers) ---")
    fns = [x for x in results_breakdown if "FN" in x["category"]]
    for x in fns[:3]:
        print(f"Q: {x['question']}")
        print(f"Got: {x['prediction_snippet']}...\n")


if __name__ == "__main__":
    calculate_confusion_matrix(csv_path)
